name: MyWebApp

on:
  push:
    branches:
    - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Check out this repo
      uses: actions/checkout@v4

    - name: Restore dependencies (install Nuget packages)
      run: dotnet restore

    - name: Build and publish the app
      run: |
        dotnet build --no-restore
        dotnet publish -c Release -o ./publish  

    - name: List contents of publish folder
      run: ls -R ./publish

    - name: Upload app artifacts to Github
      uses: actions/upload-artifact@v4
      with:
        name: app-artifacts
        path: ./publish

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Download the artifacts from Github (from the build job)
      uses: actions/download-artifact@v4
      with:
        name: app-artifacts

    - name: Start SSH Tunnel via Bastion Host
      run: |
        # Start SSH tunnel from Bastion Host and wait for it to establish
        ssh -f -N -L 2222:10.0.0.4:22 azureuser@98.71.41.249
        # Wait a bit to ensure the tunnel is established
        sleep 20
        # Check if the tunnel is up and listening on port 2222
        netstat -an | grep 2222

    - name: Test SSH Tunnel Connection
      run: |
        # Test if we can connect via the tunnel and ensure it's working
        ssh -o ConnectTimeout=10 -p 2222 azureuser@localhost 'echo Tunnel is working'

    - name: Stop the application service
      run: |
        sudo systemctl stop MyWebApp.service

    - name: Deploy the application
      run: |
        # Copy the app files to the server using SCP via the tunnel
        scp -P 2222 -r /home/azureuser/actions-runner/_work/MyWebApp/MyWebApp/* azureuser@localhost:/opt/MyWebApp/

    - name: Start the application service
      run: |
        sudo systemctl start MyWebApp.service
