name: Deploy .NET App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build & Publish
        run: |
          dotnet restore
          dotnet publish -c Release -o ./publish

      - name: Deploy to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: 20.82.143.111
          username: azureuser
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: "./publish/*"
          target: "/home/azureuser/webapp"
