name: MyWebApp

on:
  push:
    branches:
    - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Check out this repo
      uses: actions/checkout@v4

    - name: Restore dependencies (install Nuget packages)
      run: dotnet restore

    - name: Build and publish the app
      run: |
        dotnet build --no-restore
        dotnet publish -c Release -o ./publish  

    - name: List contents of publish folder
      run: ls -R ./publish

    - name: Upload app artifacts to Github
      uses: actions/upload-artifact@v4
      with:
        name: app-artifacts
        path: ./publish

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Download the artifacts from Github (from the build job)
      uses: actions/download-artifact@v4
      with:
        name: app-artifacts

    # Här borttar vi SSH-tunnel öppningen, eftersom den redan är öppen
    - name: Test if tunnel is up (using netstat)
      run: |
        netstat -an | grep 2222  # Kolla om tunneln är öppen på port 2222

    - name: Test SSH tunnel
      run: |
        # Testa om vi kan ansluta via tunneln
        ssh -p 2222 azureuser@localhost 'echo Tunnel is working'

    - name: Stop the application service
      run: |
        sudo systemctl stop MyWebApp.service

    - name: Deploy the application
      run: |
        # Kopiera filerna till servern via SCP via tunneln
        scp -P 2222 -r /home/azureuser/actions-runner/_work/MyWebApp/MyWebApp/* azureuser@localhost:/opt/MyWebApp/

    - name: Start the application service
      run: |
        sudo systemctl start MyWebApp.service
