name: MyWebApp

on:
  push:
    branches:
    - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Check out this repo
      uses: actions/checkout@v4

    - name: Restore dependencies (install Nuget packages)
      run: dotnet restore

    - name: Build and publish the app
      run: |
        dotnet build --no-restore
        dotnet publish -c Release -o ./publish  

    - name: List contents of publish folder
      run: ls -R ./publish

    - name: Upload app artifacts to Github
      uses: actions/upload-artifact@v4
      with:
        name: app-artifacts
        path: ./publish

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Download the artifacts from Github (from the build job)
      uses: actions/download-artifact@v4
      with:
        name: app-artifacts

    - name: Copy files to Reverse Proxy Server (not Bastion Host)
      run: |
        # Skicka artefakterna till Reverse Proxy Server via SCP
        scp -P 2222 -r /home/azureuser/actions-runner/_work/MyWebApp/MyWebApp/* azureuser@reverse-proxy-server-ip:/opt/MyWebApp/

    - name: Restart Reverse Proxy Server
      run: |
        # Om du har Nginx som reverse proxy, behöver du starta om den för att ladda nya filer
        sudo systemctl restart nginx

    - name: Restart the App service on the App Server
      run: |
        # Starta om appen på app-servern om det behövs
        sudo systemctl restart MyWebApp.service
